ENGLISH_WORDS = [
    'ABACK', 'ABASE', 'ABATE', 'ABBEY', 'ABBOT', 'ABHOR', 'ABIDE', 'ABLED',
    'ABODE', 'ABOUT', 'ABOVE', 'ABUSE', 'ACUTE', 'ADAPT', 'ADEPT', 'ADOBE',
    'ADOPT', 'ADULT', 'AEGIS', 'AFFIX', 'AFIRE', 'AFOOT', 'AFOUL', 'AFTER',
    'AGAIN', 'AGAPE', 'AGATE', 'AGENT', 'AGILE', 'AGING', 'AGLOW', 'AGONY',
    'AGORA', 'AGREE', 'AHEAD', 'AIDER', 'AISLE', 'ALARM', 'ALBUM', 'ALERT',
    'ALGAE', 'ALIBI', 'ALIEN', 'ALIGN', 'ALIKE', 'ALIVE', 'ALLAY', 'ALLEY',
    'ALLOT', 'ALLOW', 'ALLOY', 'ALOFT', 'ALONE', 'ALONG', 'ALOOF', 'ALOUD',
    'ALPHA', 'ALTAR', 'ALTER', 'AMASS', 'AMAZE', 'AMBER', 'AMBLE', 'AMEND',
    'AMISS', 'AMITY', 'AMONG', 'AMPLE', 'AMPLY', 'AMUSE', 'ANGEL', 'ANGER',
    'ANGLE', 'ANGRY', 'ANGST', 'ANIME', 'ANISE', 'ANKLE', 'ANNEX', 'ANNOY',
    'ANNUL', 'ANODE', 'ANTIC', 'ANVIL', 'AORTA', 'APACE', 'APART', 'APPLE',
    'APPLY', 'APRON', 'APTLY', 'ARBOR', 'ARDOR', 'ARENA', 'ARGUE', 'ARISE',
    'ARMOR', 'AROMA', 'AROSE', 'ARRAY', 'ARROW', 'ARSON', 'ARTSY', 'ASCOT',
    'ASHEN', 'ASIDE', 'ASKEW', 'ASSAY', 'ASSET', 'ATOLL', 'ATONE', 'ATTIC',
    'AUDIO', 'AUDIT', 'AUGUR', 'AUNTY', 'AVAIL', 'AVERT', 'AVIAN', 'AVOID',
    'AWAIT', 'AWAKE', 'AWARD', 'AWARE', 'AWASH', 'AWFUL', 'AWOKE', 'AXIOM',
    'AZURE', 'BABEL', 'BABES', 'BACKS', 'BACON', 'BADGE', 'BADLY', 'BAGEL',
    'BAKER', 'BALER', 'BALMY', 'BANAL', 'BANJO', 'BARGE', 'BARON', 'BASAL',
    'BASIC', 'BASIL', 'BASIN', 'BASIS', 'BASTE', 'BATCH', 'BATHE', 'BATON',
    'BATTY', 'BAWDY', 'BAYOU', 'BEACH', 'BEADY', 'BEARD', 'BEAST', 'BEECH',
    'BEEFY', 'BEGET', 'BEGIN', 'BEGUN', 'BEING', 'BELCH', 'BELIE', 'BELLE',
    'BELLY', 'BELOW', 'BENCH', 'BERET', 'BERRY', 'BERTH', 'BESET', 'BETEL',
    'BEVEL', 'BEZEL', 'BIBLE', 'BICEP', 'BIDDY', 'BIGOT', 'BILGE', 'BILLY',
    'BINGE', 'BINGO', 'BIOME', 'BIRCH', 'BIRTH', 'BISON', 'BITTY', 'BLACK',
    'BLADE', 'BLAME', 'BLAND', 'BLANK', 'BLARE', 'BLAST', 'BLAZE', 'BLEAK',
    'BLEAT', 'BLEED', 'BLEEP', 'BLEND', 'BLESS', 'BLIMP', 'BLIND', 'BLINK',
    'BLISS', 'BLITZ', 'BLOAT', 'BLOCK', 'BLOKE', 'BLOND', 'BLOOD', 'BLOOM',
    'BLOWN', 'BLUFF', 'BLUNT', 'BLURB', 'BLURT', 'BLUSH', 'BOARD', 'BOAST',
    'BOBBY', 'BONEY', 'BONGO', 'BONUS', 'BOOBY', 'BOOST', 'BOOTH', 'BOOTY',
    'BOOZE', 'BOOZY', 'BORAX', 'BORNE', 'BOSOM', 'BOSSY', 'BOTCH', 'BOUGH',
    'BOULE', 'BOUND', 'BOWEL', 'BOXER', 'BRACE', 'BRAID', 'BRAIN', 'BRAKE',
    'BRAND', 'BRASH', 'BRASS', 'BRAVE', 'BRAVO', 'BRAWL', 'BRAWN', 'BREAD',
    'BREAK', 'BREED', 'BRIAR', 'BRIBE', 'BRICK', 'BRIEF', 'BRINE', 'BRING',
    'BRINK', 'BRINY', 'BRISK', 'BROAD', 'BROIL', 'BROKE', 'BROOD', 'BROOK',
    'BROOM', 'BROTH', 'BROWN', 'BRUNT', 'BRUSH', 'BRUTE', 'BUDDY', 'BUDGE',
    'BUGGY', 'BUGLE', 'BUILD', 'BUILT', 'BULGY', 'BULLY', 'BUNCH', 'BUNNY',
    'BURLY', 'BURNT', 'BURST', 'BUSHY', 'BUTCH', 'BUTTE', 'BUXOM', 'BUYER',
    'CABAL', 'CABBY', 'CABIN', 'CABLE', 'CACAO', 'CACHE', 'CACTI', 'CADDY',
    'CADET', 'CAGEY', 'CAIRN', 'CAMEL', 'CAMEO', 'CANAL', 'CANDY', 'CANNY',
    'CANOE', 'CANON', 'CAPER', 'CAPUT', 'CARAT', 'CARGO', 'CAROL', 'CARRY',
    'CARVE', 'CASTE', 'CATCH', 'CATER', 'CATTY', 'CAULK', 'CAUSE', 'CAVIL',
    'CEASE', 'CEDAR', 'CELLO', 'CHAFE', 'CHAFF', 'CHAIN', 'CHAIR', 'CHALK',
    'CHAMP', 'CHANT', 'CHAOS', 'CHARD', 'CHARM', 'CHART', 'CHASE', 'CHASM',
    'CHEAP', 'CHEAT', 'CHECK', 'CHEEK', 'CHEER', 'CHESS', 'CHEST', 'CHICK',
    'CHIDE', 'CHIEF', 'CHILD', 'CHILI', 'CHILL', 'CHIME', 'CHINA', 'CHIRP',
    'CHOCK', 'CHOIR', 'CHOKE', 'CHORD', 'CHORE', 'CHOSE', 'CHUCK', 'CHUMP',
    'CHUNK', 'CHURN', 'CHUTE', 'CIDER', 'CIGAR', 'CINCH', 'CIRCA', 'CIVIC',
    'CIVIL', 'CLAIM', 'CLAMP', 'CLANG', 'CLANK', 'CLASH', 'CLASP', 'CLASS',
    'CLEAN', 'CLEAR', 'CLEAT', 'CLEFT', 'CLERK', 'CLICK', 'CLIFF', 'CLIMB',
    'CLING', 'CLINK', 'CLOAK', 'CLOCK', 'CLONE', 'CLOSE', 'CLOTH', 'CLOUD',
    'CLOUT', 'CLOVE', 'CLOWN', 'CLUCK', 'CLUED', 'CLUMP', 'CLUNG', 'COACH',
    'COAST', 'COBRA', 'COCOA', 'COLON', 'COLOR', 'COMET', 'COMIC', 'COMMO',
    'CONCH', 'CONDO', 'CONIC', 'COPSE', 'CORAL', 'CORER', 'CORNY', 'COUCH',
    'COUGH', 'COULD', 'COUNT', 'COURT', 'COVEN', 'COVER', 'COVET', 'COVEY',
    'CRACK', 'CRAFT', 'CRAMP', 'CRANE', 'CRANK', 'CRASH', 'CRASS', 'CRATE',
    'CRAVE', 'CRAWL', 'CRAZY', 'CREAK', 'CREAM', 'CREDO', 'CREED', 'CREEK',
    'CREEP', 'CREME', 'CREPE', 'CREPT', 'CRESS', 'CREST', 'CRICK', 'CRIED',
    'CRIER', 'CRIME', 'CRIMP', 'CRISP', 'CROAK', 'CROCK', 'CRONE', 'CRONY',
    'CROOK', 'CROON', 'CROSS', 'CROUP', 'CROWD', 'CROWN', 'CRUDE', 'CRUEL',
    'CRUMB', 'CRUMP', 'CRUSH', 'CRUST', 'CRYPT', 'CUBIC', 'CUMIN', 'CURIO',
    'CURLY', 'CURRY', 'CURSE', 'CURVE', 'CURVY', 'CUTIE', 'CYBER', 'CYCLE',
    'CYNIC', 'DADDY', 'DAILY', 'DAIRY', 'DAISY', 'DALLY', 'DANCE', 'DANDY',
    'DATED', 'DATUM', 'DAUNT', 'DEATH', 'DEBAR', 'DEBIT', 'DEBUG', 'DEBUT',
    'DECAL', 'DECAY', 'DECOR', 'DECOY', 'DECRY', 'DEFER', 'DEIGN', 'DEITY',
    'DELAY', 'DELTA', 'DELVE', 'DEMON', 'DEMUR', 'DENIM', 'DEPOT', 'DEPTH',
    'DERBY', 'DETER', 'DETOX', 'DEUCE', 'DEVIL', 'DIARY', 'DICEY', 'DIGIT',
    'DILLY', 'DIMLY', 'DINER', 'DINGO', 'DINGY', 'DIODE', 'DIRGE', 'DIRTY',
    'DISCO', 'DITCH', 'DITTO', 'DITTY', 'DIVER', 'DIZZY', 'DODGE', 'DODGY',
    'DOGMA', 'DOING', 'DOLLY', 'DONOR', 'DONUT', 'DOPEY', 'DOUBT', 'DOUGH',
    'DOWDY', 'DOWEL', 'DOWNY', 'DOWRY', 'DRAFT', 'DRAIN', 'DRAKE', 'DRAMA',
    'DRANK', 'DRAPE', 'DRAWL', 'DRAWN', 'DREAD', 'DREAM', 'DRESS', 'DRIED',
    'DRIER', 'DRIFT', 'DRILL', 'DRINK', 'DRIVE', 'DROIT', 'DROLL', 'DRONE',
    'DROOP', 'DROSS', 'DROVE', 'DROWN', 'DRUID', 'DRUNK', 'DRYLY', 'DUCHY',
    'DULLY', 'DUMMY', 'DUMPY', 'DUNCE', 'DUSKY', 'DUSTY', 'DUTCH', 'DUVET',
    'DWARF', 'DWELL', 'DWELT', 'DYING', 'EAGER', 'EAGLE', 'EARLY', 'EARTH',
    'EASEL', 'EATEN', 'EATER', 'EBONY', 'ECLAT', 'EDICT', 'EDIFY', 'EERIE',
    'EGRET', 'EIGHT', 'EJECT', 'EKING', 'ELATE', 'ELBOW', 'ELDER', 'ELECT',
    'ELEGY', 'ELFIN', 'ELIDE', 'ELITE', 'ELOPE', 'ELUDE', 'EMAIL', 'EMBED',
    'EMBER', 'EMCEE', 'EMPTY', 'ENACT', 'ENDOW', 'ENEMA', 'ENEMY', 'ENJOY',
    'ENNUI', 'ENSUE', 'ENTER', 'ENTRY', 'ENVOY', 'EPOCH', 'EPOXY', 'EQUAL',
    'EQUIP', 'ERASE', 'ERECT', 'ERODE', 'ERROR', 'ERUPT', 'ESSAY', 'ESTER',
    'ETHIC', 'ETHOS', 'ETUDE', 'EVADE', 'EVENT', 'EVERY', 'EVICT', 'EVOKE',
    'EXACT', 'EXALT', 'EXCEL', 'EXERT', 'EXILE', 'EXIST', 'EXPEL', 'EXTRA',
    'EXULT', 'EYING', 'FABLE', 'FACET', 'FAINT', 'FAIRY', 'FAITH', 'FALSE',
    'FAMED', 'FANCY', 'FANNY', 'FARCE', 'FATAL', 'FATTY', 'FAULT', 'FAUNA',
    'FAVOR', 'FEAST', 'FECAL', 'FEIGN', 'FELLA', 'FELON', 'FEMME', 'FEMUR',
    'FENCE', 'FERAL', 'FERRY', 'FETAL', 'FETCH', 'FETID', 'FETUS', 'FEVER',
    'FEWER', 'FIBER', 'FICUS', 'FIELD', 'FIEND', 'FIFTH', 'FIFTY', 'FIGHT',
    'FILCH', 'FILET', 'FILLY', 'FILMY', 'FILTH', 'FINAL', 'FINCH', 'FINER',
    'FIRST', 'FISHY', 'FIXER', 'FIZZY', 'FJORD', 'FLACK', 'FLAIL', 'FLAIR',
    'FLAKE', 'FLAKY', 'FLAME', 'FLANK', 'FLARE', 'FLASH', 'FLASK', 'FLECK',
    'FLEET', 'FLESH', 'FLICK', 'FLIER', 'FLING', 'FLINT', 'FLIRT', 'FLOAT',
    'FLOCK', 'FLOOD', 'FLOOR', 'FLORA', 'FLOSS', 'FLOUR', 'FLOUT', 'FLOWN',
    'FLUFF', 'FLUID', 'FLUKE', 'FLUME', 'FLUNG', 'FLUNK', 'FLUSH', 'FLUTE',
    'FLYER', 'FOAMY', 'FOCAL', 'FOCUS', 'FOGGY', 'FOIST', 'FOLIO', 'FOLLY',
    'FORAY', 'FORCE', 'FORGE', 'FORGO', 'FORTE', 'FORTH', 'FORTY', 'FORUM',
    'FOUND', 'FOYER', 'FRAIL', 'FRAME', 'FRANK', 'FRAUD', 'FREAK', 'FREED',
    'FREER', 'FRESH', 'FRIAR', 'FRIED', 'FRILL', 'FRISK', 'FRITZ', 'FROCK',
    'FROND', 'FRONT', 'FROST', 'FROTH', 'FROWN', 'FRUIT', 'FUDGE', 'FUGUE',
    'FULLY', 'FUNGI', 'FUNKY', 'FUNNY', 'FUROR', 'FUSSY', 'FUZZY', 'GAFFE',
    'GAILY', 'GAMER', 'GAMMA', 'GAMUT', 'GASSY', 'GAUDY', 'GAUGE', 'GAUNT',
    'GAUZE', 'GAVEL', 'GAWKY', 'GAYER', 'GAYLY', 'GAZER', 'GECKO', 'GEEKY',
    'GEESE', 'GENIE', 'GENRE', 'GHOST', 'GHOUL', 'GIANT', 'GIDDY', 'GIPSY',
    'GIRLY', 'GIRTH', 'GIVEN', 'GIVER', 'GLADE', 'GLAND', 'GLARE', 'GLASS',
    'GLAZE', 'GLEAM', 'GLEAN', 'GLIDE', 'GLINT', 'GLOAT', 'GLOBE', 'GLOOM',
    'GLORY', 'GLOSS', 'GLOVE', 'GLYPH', 'GNASH', 'GNOME', 'GODLY', 'GOING',
    'GOLEM', 'GOLLY', 'GONAD', 'GONER', 'GOODY', 'GOOEY', 'GOOFY', 'GOOSE',
    'GORGE', 'GOUGE', 'GOURD', 'GRACE', 'GRADE', 'GRAFT', 'GRAIN', 'GRAND',
    'GRANT', 'GRAPE', 'GRAPH', 'GRASP', 'GRASS', 'GRATE', 'GRAVE', 'GRAVY',
    'GRAZE', 'GREAT', 'GREED', 'GREEN', 'GREET', 'GRIEF', 'GRILL', 'GRIME',
    'GRIMY', 'GRIND', 'GRIPE', 'GROAN', 'GROIN', 'GROOM', 'GROPE', 'GROSS',
    'GROUP', 'GROUT', 'GROVE', 'GROWL', 'GROWN', 'GRUEL', 'GRUFF', 'GRUNT',
    'GUARD', 'GUAVA', 'GUESS', 'GUEST', 'GUIDE', 'GUILD', 'GUILE', 'GULCH',
    'GULLY', 'GUPPY', 'GUSTO', 'GUSTY', 'GYPSY', 'HABIT', 'HAIRY', 'HALVE',
    'HANDY', 'HAPPY', 'HARDY', 'HAREM', 'HARPY', 'HARRY', 'HARSH', 'HASTE',
    'HASTY', 'HATCH', 'HATER', 'HAUNT', 'HAUTE', 'HAVEN', 'HAVOC', 'HAZEL',
    'HEADY', 'HEARD', 'HEART', 'HEATH', 'HEAVE', 'HEAVY', 'HEDGE', 'HEFTY',
    'HEIST', 'HELIX', 'HELLO', 'HENCE', 'HERON', 'HILLY', 'HINGE', 'HIPPO',
    'HIPPY', 'HITCH', 'HOARD', 'HOBBY', 'HOIST', 'HOLLY', 'HOMER', 'HONEY',
    'HONOR', 'HORDE', 'HORNY', 'HORSE', 'HOTEL', 'HOTLY', 'HOUND', 'HOUSE',
    'HOVEL', 'HOVER', 'HOWDY', 'HUMAN', 'HUMID', 'HUMOR', 'HUMPH', 'HUMUS',
    'HUNCH', 'HUNKY', 'HURRY', 'HUSKY', 'HUSSY', 'HUTCH', 'HYDRO', 'HYENA',
    'HYMEN', 'ICING', 'IDEAL', 'IDIOM', 'IDIOT', 'IDLER', 'IGLOO', 'ILIAC',
    'IMAGE', 'IMBUE', 'IMPEL', 'IMPLY', 'INANE', 'INBOX', 'INCUR', 'INDEX',
    'INEPT', 'INERT', 'INFER', 'INGOT', 'INLAY', 'INLET', 'INNER', 'INPUT',
    'INTER', 'INTRO', 'IONIC', 'IRATE', 'IRONY', 'ISLET', 'ISSUE', 'ITCHY',
    'IVORY', 'JAUNT', 'JAZZY', 'JELLY', 'JERKY', 'JETTY', 'JEWEL', 'JIFFY',
    'JOINT', 'JOIST', 'JOKER', 'JOLLY', 'JOUST', 'JUDGE', 'JUICE', 'JUICY',
    'JUMBO', 'JUMPY', 'JUNTA', 'JUNTO', 'JUROR', 'KAPOK', 'KAPUT', 'KAYAK',
    'KEBAB', 'KHAKI', 'KIOSK', 'KITTY', 'KNACK', 'KNAVE', 'KNEAD', 'KNEEL',
    'KNELT', 'KNIFE', 'KNOCK', 'KNOLL', 'KNOWN', 'KOALA', 'KRILL', 'LABEL',
    'LABOR', 'LADEN', 'LADLE', 'LAGER', 'LANCE', 'LANKY', 'LAPEL', 'LAPSE',
    'LARGE', 'LARVA', 'LASSO', 'LATCH', 'LATER', 'LATHE', 'LATTE', 'LAUGH',
    'LAYER', 'LEACH', 'LEAFY', 'LEAKY', 'LEANT', 'LEAPT', 'LEARN', 'LEASE',
    'LEASH', 'LEAST', 'LEAVE', 'LEDGE', 'LEECH', 'LEERY', 'LEFTY', 'LEGAL',
    'LEGGY', 'LEMON', 'LEMUR', 'LEPER', 'LEVEL', 'LEVER', 'LIBEL', 'LIEGE',
    'LIGHT', 'LIKEN', 'LILAC', 'LIMBO', 'LIMIT', 'LINEN', 'LINER', 'LINGO',
    'LIPID', 'LITHE', 'LIVED', 'LIVER', 'LIVID', 'LLAMA', 'LOCAL', 'LODGE',
    'LOFTY', 'LOGIC', 'LOGIN', 'LOOPY', 'LOOSE', 'LORRY', 'LOSER', 'LOUSE',
    'LOUSY', 'LOVER', 'LOWER', 'LOWLY', 'LOYAL', 'LUCID', 'LUCKY', 'LUMPY',
    'LUNAR', 'LUNCH', 'LUNGE', 'LUPUS', 'LURCH', 'LURID', 'LYMPH', 'LYRIC',
    'MACAW', 'MACHO', 'MACRO', 'MADAM', 'MADLY', 'MAFIA', 'MAGIC', 'MAGMA',
    'MAIZE', 'MAJOR', 'MAKER', 'MAMBO', 'MAMMA', 'MAMMY', 'MANGA', 'MANGE',
    'MANGO', 'MANGY', 'MANIA', 'MANIC', 'MANLY', 'MANOR', 'MAPLE', 'MARCH',
    'MARRY', 'MARSH', 'MASON', 'MASSE', 'MATCH', 'MATED', 'MATEY', 'MAUVE',
    'MAXIM', 'MAYBE', 'MAYOR', 'MEALY', 'MEANT', 'MEATY', 'MECCA', 'MEDAL',
    'MEDIA', 'MEDIC', 'MELEE', 'MELON', 'MERCY', 'MERGE', 'MERIT', 'MERRY',
    'METAL', 'METER', 'METRO', 'MICRO', 'MIDGE', 'MIDST', 'MIMIC', 'MINCE',
    'MINER', 'MINOR', 'MINTY', 'MINUS', 'MISER', 'MOCHA', 'MODAL', 'MODEL',
    'MODEM', 'MOGUL', 'MOIST', 'MOLAR', 'MOLDY', 'MOMMY', 'MONEY', 'MONTH',
    'MOODY', 'MOOSE', 'MORAL', 'MORON', 'MORPH', 'MOSSY', 'MOTEL', 'MOTIF',
    'MOTOR', 'MOTTO', 'MOULT', 'MOUND', 'MOUNT', 'MOURN', 'MOUSE', 'MOUTH',
    'MOVER', 'MOVIE', 'MOWER', 'MUCUS', 'MUDDY', 'MULCH', 'MUMMY', 'MUNCH',
    'MURAL', 'MURKY', 'MUSHY', 'MUSIC', 'MUSKY', 'MUSTY', 'MYRRH', 'NADIR',
    'NAIVE', 'NANNY', 'NASAL', 'NASTY', 'NATAL', 'NAVAL', 'NAVEL', 'NEEDY',
    'NEIGH', 'NERDY', 'NERVE', 'NEVER', 'NEWER', 'NEWLY', 'NICER', 'NICHE',
    'NIECE', 'NIGHT', 'NINJA', 'NINTH', 'NOBLE', 'NOBLY', 'NOISE', 'NOISY',
    'NOMAD', 'NOOSE', 'NORTH', 'NOSEY', 'NOTCH', 'NOVEL', 'NUDGE', 'NURSE',
    'NUTTY', 'NYLON', 'OAKEN', 'OBESE', 'OCCUR', 'OCEAN', 'OCTAL', 'OCTET',
    'ODDER', 'ODDLY', 'OFFAL', 'OFFER', 'OFTEN', 'OLDEN', 'OLDER', 'OLIVE',
    'OMBRE', 'OMEGA', 'ONION', 'ONSET', 'OPERA', 'OPINE', 'OPIUM', 'OPTIC',
    'ORBIT', 'ORDER', 'ORGAN', 'OTHER', 'OTTER', 'OUGHT', 'OUNCE', 'OUTER',
    'OUTGO', 'OVARY', 'OVATE', 'OVERT', 'OWING', 'OWNER', 'OXIDE', 'PACER',
    'PADDY', 'PAGAN', 'PAINT', 'PALER', 'PALSY', 'PANEL', 'PANIC', 'PANSY',
    'PAPAL', 'PAPER', 'PARER', 'PARKA', 'PARRY', 'PARSE', 'PARTY', 'PASTA',
    'PASTE', 'PASTY', 'PATCH', 'PATIO', 'PATSY', 'PATTY', 'PAUSE', 'PAYEE',
    'PAYER', 'PEACE', 'PEACH', 'PEARL', 'PECAN', 'PEDAL', 'PENAL', 'PENCE',
    'PENNY', 'PERCH', 'PERIL', 'PERKY', 'PESKY', 'PESTO', 'PETAL', 'PETTY',
    'PHASE', 'PHONE', 'PHONY', 'PHOTO', 'PIANO', 'PICKY', 'PIECE', 'PIETY',
    'PIGGY', 'PILOT', 'PINCH', 'PINEY', 'PINKY', 'PINTO', 'PIPER', 'PIQUE',
    'PITCH', 'PITHY', 'PIVOT', 'PIXEL', 'PIXIE', 'PLACE', 'PLAID', 'PLAIN',
    'PLAIT', 'PLANE', 'PLANK', 'PLANT', 'PLATE', 'PLAZA', 'PLEAD', 'PLEAT',
    'PLIED', 'PLIER', 'PLUCK', 'PLUMB', 'PLUME', 'PLUMP', 'PLUNK', 'PLUSH',
    'POACH', 'PODIA', 'POINT', 'POISE', 'POKER', 'POLAR', 'POLKA', 'POLYP',
    'POOCH', 'POPPY', 'PORCH', 'POSER', 'POSIT', 'POSSE', 'POUCH', 'POUND',
    'POUTY', 'POWER', 'PRANK', 'PRAWN', 'PREEN', 'PRESS', 'PRICE', 'PRICK',
    'PRIDE', 'PRIED', 'PRIME', 'PRIMP', 'PRINT', 'PRIOR', 'PRISM', 'PRIVY',
    'PRIZE', 'PROBE', 'PRONE', 'PRONG', 'PROOF', 'PROSE', 'PROUD', 'PROVE',
    'PROWL', 'PROXY', 'PRUDE', 'PRUNE', 'PSALM', 'PUBIC', 'PUDGY', 'PUFFY',
    'PULPY', 'PULSE', 'PUNCH', 'PUPIL', 'PUPPY', 'PUREE', 'PURER', 'PURGE',
    'PURSE', 'PUSHY', 'PUTTY', 'PYGMY', 'QUACK', 'QUAIL', 'QUAKE', 'QUALM',
    'QUARK', 'QUART', 'QUASH', 'QUASI', 'QUEEN', 'QUEER', 'QUELL', 'QUERY',
    'QUEST', 'QUEUE', 'QUICK', 'QUIDS', 'QUIET', 'QUILL', 'QUILT', 'QUIRK',
    'QUITE', 'QUOTA', 'QUOTE', 'QUOTH', 'RABBI', 'RABID', 'RACER', 'RADAR',
    'RADII', 'RADIO', 'RAINY', 'RAISE', 'RAJAH', 'RALLY', 'RALPH', 'RAMEN',
    'RANCH', 'RANDY', 'RANGE', 'RAPID', 'RARER', 'RASPY', 'RATIO', 'RATTY',
    'RAVEN', 'RAYON', 'REACH', 'REACT', 'READY', 'REALM', 'REARM', 'REBAR',
    'REBEL', 'REBUS', 'REBUT', 'RECAP', 'RECUR', 'RECUT', 'REEDY', 'REFER',
    'REFIT', 'REGAL', 'REHAB', 'REIGN', 'RELAX', 'RELAY', 'RELIC', 'REMIT',
    'RENAL', 'RENEW', 'REPAY', 'REPEL', 'REPLY', 'RETRO', 'RETRY', 'RIDER',
    'RIDGE', 'RIFLE', 'RIGHT', 'RIGID', 'RIGOR', 'RINSE', 'RIPEN', 'RISEN',
    'RISKY', 'RIVAL', 'RIVER', 'ROAST', 'ROBIN', 'ROBOT', 'ROCKY', 'ROGUE',
    'ROOMY', 'ROOST', 'ROOTS', 'ROUGH', 'ROUND', 'ROUTE', 'ROVER', 'ROYAL',
    'RUGBY', 'RULER', 'RUMOR', 'RURAL', 'SADLY', 'SAFER', 'SAINT', 'SALAD',
    'SALON', 'SALSA', 'SALTY', 'SANDY', 'SATIN', 'SAUCE', 'SAVER', 'SCALE',
    'SCARE', 'SCARF', 'SCARY', 'SCENE', 'SCENT', 'SCOPE', 'SCORE', 'SCOUT',
    'SCRAP', 'SCREW', 'SEIZE', 'SENSE', 'SERVE', 'SEVEN', 'SHADE', 'SHADY',
    'SHAKE', 'SHALL', 'SHAME', 'SHAPE', 'SHARE', 'SHARK', 'SHARP', 'SHEEP',
    'SHEER', 'SHEET', 'SHELF', 'SHELL', 'SHIFT', 'SHINE', 'SHINY', 'SHIRT',
    'SHOCK', 'SHORE', 'SHORT', 'SHOUT', 'SHOWN', 'SIGHT', 'SILLY', 'SINCE',
    'SIXTH', 'SKILL', 'SKIRT', 'SKULL', 'SLATE', 'SLEEP', 'SLICE', 'SLIDE',
    'SLOPE', 'SMALL', 'SMART', 'SMELL', 'SMILE', 'SMOKE', 'SNAKE', 'SOLAR',
    'SOLID', 'SOLVE', 'SORRY', 'SOUND', 'SOUTH', 'SPACE', 'SPADE', 'SPARE',
    'SPARK', 'SPEAK', 'SPEED', 'SPELL', 'SPEND', 'SPICE', 'SPICY', 'SPIKE',
    'SPILL', 'SPINE', 'SPLIT', 'SPOON', 'SPORT', 'SPRAY', 'STACK', 'STAFF',
    'STAGE', 'STAIR', 'STAKE', 'STALE', 'STAMP', 'STAND', 'STARE', 'START',
    'STATE', 'STEAK', 'STEAL', 'STEAM', 'STEEL', 'STEEP', 'STICK', 'STILL',
    'STOCK', 'STONE', 'STOOD', 'STORE', 'STORM', 'STORY', 'STRAW', 'STRIP',
    'STUCK', 'STUDY', 'STUFF', 'STYLE', 'SUGAR', 'SUITE', 'SUNNY', 'SUPER',
    'SURGE', 'SWEAR', 'SWEAT', 'SWEEP', 'SWEET', 'SWIFT', 'SWING', 'SWORD',
    'TABLE', 'TAKEN', 'TASTE', 'TEACH', 'TEETH', 'THANK', 'THEIR', 'THEME',
    'THERE', 'THESE', 'THICK', 'THIEF', 'THIGH', 'THING', 'THINK', 'THIRD',
    'THOSE', 'THREE', 'THROW', 'THUMB', 'TIDES', 'TIGER', 'TIGHT', 'TIMER',
    'TIRED', 'TITLE', 'TOAST', 'TODAY', 'TOKEN', 'TONIC', 'TOOTH', 'TOPIC',
    'TORCH', 'TOTAL', 'TOUCH', 'TOUGH', 'TOWER', 'TOXIC', 'TRACE', 'TRACK',
    'TRADE', 'TRAIL', 'TRAIN', 'TRAIT', 'TRASH', 'TREAT', 'TREND', 'TRIAL',
    'TRIBE', 'TRICK', 'TRIED', 'TROOP', 'TRUCK', 'TRULY', 'TRUNK', 'TRUST',
    'TRUTH', 'TWICE', 'TWIST', 'ULTRA', 'UNCLE', 'UNDER', 'UNIFY', 'UNION',
    'UNITE', 'UNITY', 'UNTIL', 'UPPER', 'URBAN', 'USAGE', 'USUAL', 'UTTER',
    'UVULA', 'VAGUE', 'VALET', 'VALID', 'VALUE', 'VALVE', 'VAPID', 'VAPOR',
    'VAULT', 'VAUNT', 'VEGAN', 'VENOM', 'VENUE', 'VERGE', 'VERSE', 'VERSO',
    'VERVE', 'VICAR', 'VIDEO', 'VIGIL', 'VIGOR', 'VILLA', 'VINYL', 'VIOLA',
    'VIPER', 'VIRAL', 'VIRUS', 'VISIT', 'VISOR', 'VISTA', 'VITAL', 'VIVID',
    'VIXEN', 'VOCAL', 'VODKA', 'VOICE', 'VOILE', 'VOMIT', 'VOTER', 'VOUCH',
    'VOWEL', 'VYING', 'WACKY', 'WAFER', 'WAGER', 'WAGON', 'WAIST', 'WAIVE',
    'WALTZ', 'WARTY', 'WASTE', 'WATCH', 'WATER', 'WAVER', 'WAXEN', 'WEARY',
    'WEAVE', 'WEDGE', 'WEEDY', 'WEIGH', 'WELCH', 'WELSH', 'WHACK', 'WHALE',
    'WHARF', 'WHEAT', 'WHEEL', 'WHELP', 'WHERE', 'WHICH', 'WHIFF', 'WHILE',
    'WHINE', 'WHIRL', 'WHISK', 'WHITE', 'WHOLE', 'WHOOP', 'WHOSE', 'WIDEN',
    'WIDER', 'WIDOW', 'WIDTH', 'WIELD', 'WIGHT', 'WILLY', 'WIMPY', 'WINCE',
    'WINCH', 'WINDY', 'WISER', 'WISPY', 'WITCH', 'WITTY', 'WOKEN', 'WOMAN',
    'WOMEN', 'WOODY', 'WOOER', 'WOOLY', 'WOOZY', 'WORDY', 'WORLD', 'WORRY',
    'WORSE', 'WORST', 'WORTH', 'WOULD', 'WOUND', 'WOVEN', 'WRACK', 'WRATH',
    'WREAK', 'WRECK', 'WREST', 'WRING', 'WRIST', 'WRITE', 'WRONG', 'WROTE',
    'WRUNG', 'WRYLY', 'XENON', 'XYLEM', 'YACHT', 'YEARN', 'YEAST', 'YIELD',
    'YOUNG', 'YOUTH', 'ZEBRA', 'ZESTY', 'ZONAL',
]


def _validate_word_bank():
    """Catch invalid entries immediately when this file is edited later."""
    if not ENGLISH_WORDS:
        raise ValueError('The word bank must not be empty.')
    seen = set()
    for word in ENGLISH_WORDS:
        if (not isinstance(word, str) or len(word) != 5
                or any(letter not in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' for letter in word)):
            raise ValueError(f'Invalid word bank entry: {word!r}. Use five uppercase A-Z letters.')
        if word in seen:
            raise ValueError(f'Duplicate word bank entry: {word!r}.')
        seen.add(word)


_validate_word_bank()


def load_valid_words(words=None):
    """Return a sorted, unique five-letter A-Z vocabulary for puzzle selection.

    The bundled bank is checked at import time. Custom banks are filtered so
    invalid entries cannot accidentally become puzzle answers.
    """
    import string
    from wordle import WORD_LENGTH

    entries = ENGLISH_WORDS if words is None else words
    if isinstance(entries, (str, bytes)):
        raise ValueError('Word bank must be a collection of words.')
    try:
        iterator = iter(entries)
    except TypeError as error:
        raise ValueError('Word bank must be a collection of words.') from error
    cleaned = set()
    for word in iterator:
        if not isinstance(word, str):
            continue
        word = word.strip()
        if len(word) == WORD_LENGTH and all(c in string.ascii_letters for c in word):
            cleaned.add(word.upper())
    if not cleaned:
        raise ValueError('The word bank has no valid five-letter words.')
    return sorted(cleaned)
